spring.application.name=training_curriculum_java
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/training_curriculum_java
spring.datasource.username=masa_pond
spring.datasource.password=Masaarrow0117
spring.flyway.baselineOnMigrate=true